data=read.csv2("household_power_consumption.txt", header=TRUE)
data$Date <- as.Date(data$Date, format="%d/%m/%Y")
dif <- data[(data$Date=="2007-02-01") | (data$Date=="2007-02-02"),]
dif$Global_active_power <- as.numeric(as.character(dif$Global_active_power))
dif$Global_reactive_power <- as.numeric(as.character(dif$Global_reactive_power))
dif$Voltage <- as.numeric(as.character(dif$Voltage))
dif <- transform(dif, timestamp=as.POSIXct(paste(Date, Time)), "%d/%m/%Y %H:%M:%S")
dif$Sub_metering_1 <- as.numeric(as.character(dif$Sub_metering_1))
dif$Sub_metering_2 <- as.numeric(as.character(dif$Sub_metering_2))
dif$Sub_metering_3 <- as.numeric(as.character(dif$Sub_metering_3))
hist(dif$Global_active_power, main = paste("Global Active Power"), col="red", xlab="Global Active Power (kilowatts)")
dev.copy(png, file="plot1.png", width=480, height=480)
dev.off()
cat("Plot1.png has been saved in", getwd())